sudo: false
language: node_js
node_js:
    - "stable"
    - "4"
    - "6"
    - "7"
    - "8"

cache:
    directories:
        - node_modules

matrix:
    fast_finish: true

before_script:
    - npm run lint

script:
    - node --version
    - npm --version
    - npm run test

after_script:
    - npm run lint:debug
    - npm run lint:fix
    - npm run build
